### ISSUE TITLE
Regex Denial of Service in underscore.string

### ISSUE THREAD

**Issue by DrewRomanyk** [gruntjs/grunt-legacy-util#24]
Medium severity vulnerability found in underscore.string

* desc: Regular Expression Denial of Service
* from: grunt > grunt-legacy-util
* More info > https://www.npmjs.com/advisories/745

**Comment by shama** [comment]
Since the dependency is tagged with `~3.3.4`, it will install the latest patch version `3.3.5` with the security fix: https://github.com/gruntjs/grunt-legacy-util/blob/master/package.json#L32

If you're still getting an old version cached, delete your `package-lock.json` and `npm install` again.

**Comment by rustybailey** [comment]
Snyk is still showing a vulnerability because of underscore.string (https://snyk.io/test/npm/grunt-legacy-util/2.0.1). I looked to see why that may be happening. There was an issue created (https://github.com/esamattis/underscore.string/issues/510) in underscore.string repo in 2017, and it was supposed to have been fixed in this PR (https://github.com/esamattis/underscore.string/pull/517). However, reading through that issue thread, it looks as though the dist file wasn’t compiled (https://github.com/esamattis/underscore.string/issues/510#issuecomment-501031057) after that fix was implemented, so the vulnerability is still being distributed in npm. Someone tried to submit a PR to recompile dist (https://github.com/esamattis/underscore.string/issues/510#issuecomment-583753514), but it hasn't gotten any attention in over a year.

Is it possible to remove this dependency so that this codebase (and therefore grunt itself) can get rid of this vulnerability?

**Comment by MengRS** [comment]
I am facing the same issue as @rustybailey.... can we get an answer to his question please?
